// Package transformer provides utilities for normalising and transforming
// DriftReport resource fields before export or further processing.
//
// # Overview
//
// The transformer package exposes a single Apply function that mutates a
// DriftReport in-place based on a set of configurable options:
//
//   - NormalizeIDs   – trims whitespace and lower-cases all resource IDs.
//   - UppercaseTypes – upper-cases all resource type strings.
//   - StripPrefix    – removes a fixed string prefix from every resource ID.
//
// These transformations help produce deterministic output when reports are
// generated by different Terraform providers or CI environments that may
// apply inconsistent casing or path prefixes.
//
// # Usage
//
//	opt := transformer.Option{NormalizeIDs: true, StripPrefix: "aws:/"}
//	transformer.Apply(report, opt)
package transformer
